# Generated by Django 5.1.1 on 2024-10-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_icon'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='icon',
            table='icons',
        ),
    ]
