# Generated by Django 5.1.1 on 2024-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_icon_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='class_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
