# Generated by Django 5.1.1 on 2024-10-07 11:17

import transaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_category_category_type_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=transaction.models.Transaction.transaction_upload_to),
        ),
    ]
