# Generated by Django 5.1.1 on 2024-10-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_icon_table'),
        ('wallet', '0002_alter_wallet_initial_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon'),
        ),
    ]
