currencies = [
    {
        "code": "USD",
        "name": "United States Dollar",
        "symbol": "$",
        "country": "United States",
    },
    {"code": "EUR", "name": "Euro", "symbol": "€", "country": "Eurozone"},
    {"code": "JPY", "name": "Japanese Yen", "symbol": "¥", "country": "Japan"},
    {
        "code": "GBP",
        "name": "British Pound Sterling",
        "symbol": "£",
        "country": "United Kingdom",
    },
    {
        "code": "AUD",
        "name": "Australian Dollar",
        "symbol": "A$",
        "country": "Australia",
    },
    {"code": "CAD", "name": "Canadian Dollar", "symbol": "C$", "country": "Canada"},
    {"code": "CHF", "name": "Swiss Franc", "symbol": "CHF", "country": "Switzerland"},
    {"code": "CNY", "name": "Chinese Yuan", "symbol": "¥", "country": "China"},
    {"code": "INR", "name": "Indian Rupee", "symbol": "₹", "country": "India"},
    {"code": "RUB", "name": "Russian Ruble", "symbol": "₽", "country": "Russia"},
    {
        "code": "ZAR",
        "name": "South African Rand",
        "symbol": "R",
        "country": "South Africa",
    },
    {"code": "BRL", "name": "Brazilian Real", "symbol": "R$", "country": "Brazil"},
    {"code": "MXN", "name": "Mexican Peso", "symbol": "$", "country": "Mexico"},
    {"code": "SGD", "name": "Singapore Dollar", "symbol": "S$", "country": "Singapore"},
    {
        "code": "HKD",
        "name": "Hong Kong Dollar",
        "symbol": "HK$",
        "country": "Hong Kong",
    },
    {
        "code": "NZD",
        "name": "New Zealand Dollar",
        "symbol": "NZ$",
        "country": "New Zealand",
    },
    {"code": "NOK", "name": "Norwegian Krone", "symbol": "kr", "country": "Norway"},
    {"code": "SEK", "name": "Swedish Krona", "symbol": "kr", "country": "Sweden"},
    {"code": "DKK", "name": "Danish Krone", "symbol": "kr", "country": "Denmark"},
    {"code": "TRY", "name": "Turkish Lira", "symbol": "₺", "country": "Turkey"},
    {"code": "SAR", "name": "Saudi Riyal", "symbol": "ر.س", "country": "Saudi Arabia"},
    {
        "code": "AED",
        "name": "UAE Dirham",
        "symbol": "د.إ",
        "country": "United Arab Emirates",
    },
    {"code": "THB", "name": "Thai Baht", "symbol": "฿", "country": "Thailand"},
    {"code": "ILS", "name": "Israeli New Shekel", "symbol": "₪", "country": "Israel"},
    {"code": "PHP", "name": "Philippine Peso", "symbol": "₱", "country": "Philippines"},
    {"code": "MYR", "name": "Malaysian Ringgit", "symbol": "RM", "country": "Malaysia"},
    {"code": "CLP", "name": "Chilean Peso", "symbol": "$", "country": "Chile"},
    {"code": "COP", "name": "Colombian Peso", "symbol": "$", "country": "Colombia"},
    {"code": "VND", "name": "Vietnamese Dong", "symbol": "₫", "country": "Vietnam"},
    {
        "code": "IDR",
        "name": "Indonesian Rupiah",
        "symbol": "Rp",
        "country": "Indonesia",
    },
    {"code": "PKR", "name": "Pakistani Rupee", "symbol": "₨", "country": "Pakistan"},
    {"code": "NPR", "name": "Nepali Rupee", "symbol": "Rs", "country": "Nepal"},
]
